# Generated by Django 3.1.2 on 2020-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'Árticulo', 'verbose_name_plural': 'Árticulos'},
        ),
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
