# Generated by Django 3.1.2 on 2020-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20201015_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
